packages:
  - packages/*

catalog:
  '@changesets/cli': ^2.29.6
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@commitlint/lint': ^19.8.1
  '@commitlint/load': ^19.8.1
  '@commitlint/types': ^19.8.1
  '@cspell/cspell-types': ^9.2.1
  '@eslint/config-helpers': ^0.3.1
  '@eslint/config-inspector': ^1.2.0
  '@eslint/js': ^9.33.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@types/minimist': ^1.2.5
  '@types/node': ^20.19.11
  '@types/normalize-package-data': ^2.4.4
  '@typescript-eslint/utils': ^8.39.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  cosmiconfig-typescript-loader: ^6.1.0
  cosmiconfig: ^9.0.0
  cspell: ^9.2.1
  escape-string-regexp: ^5.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-jsdoc: ^54.1.0
  eslint-plugin-n: ^17.21.3
  eslint-plugin-unicorn: ^60.0.0
  eslint: ^9.34.0
  execa: ^9.6.0
  find-up: ^7.0.0
  globals: ^16.3.0
  globby: ^14.1.0
  husky: ^9.1.7
  jiti: ^2.5.1
  minimist: ^1.2.8
  normalize-package-data: ^8.0.0
  p-queue: ^8.1.0
  prettier-plugin-organize-attributes: ^1.0.0
  prettier: ^3.6.2
  turbo: ^2.5.6
  type-fest: ^4.41.0
  typedoc-github-theme: ^0.3.1
  typedoc-plugin-mdn-links: ^5.0.9
  typedoc: ^0.28.12
  typescript-eslint: ^8.41.0
  typescript: ^5.9.2
  vitest: ^3.2.4
  yaml: ^2.8.1
  yoctocolors: ^2.1.1
  zod-validation-error: ^4.0.1
  zod: ^4.1.5

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

onlyBuiltDependencies:
  - esbuild

verifyDepsBeforeRun: prompt
