packages:
  - packages/*

catalog:

catalogMode: strict

catalogs:
  core:
    '@ianvs/prettier-plugin-sort-imports': ^4.6.2
    '@types/node': ^20.19.11
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.34.0
    jiti: ^2.5.1
    prettier: ^3.6.2
    prettier-plugin-organize-attributes: ^1.0.0
    typescript: ^5.9.2
    vitest: ^3.2.4
  packages:
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/lint': ^19.8.1
    '@commitlint/load': ^19.8.1
    '@commitlint/types': ^19.8.1
    '@cspell/cspell-types': ^9.2.0
    '@eslint/config-helpers': ^0.3.1
    '@eslint/config-inspector': ^1.2.0
    '@eslint/js': ^9.33.0
    '@typescript-eslint/utils': ^8.39.1
    cspell: ^9.2.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-jsdoc: ^54.1.0
    eslint-plugin-n: ^17.21.3
    eslint-plugin-unicorn: ^60.0.0
    globals: ^16.3.0
    type-fest: ^4.41.0
    typescript-eslint: ^8.39.1
  root:
    '@changesets/cli': ^2.29.6
    '@commitlint/cli': ^19.8.1
    cspell: ^9.2.0
    husky: ^9.1.7
    turbo: ^2.5.6
    typedoc: ^0.28.10
    typedoc-github-theme: ^0.3.0
    typedoc-plugin-mdn-links: ^5.0.8

cleanupUnusedCatalogs: true

engineStrict: true

onlyBuiltDependencies:
  - esbuild

verifyDepsBeforeRun: prompt
