packages:
  - packages/*

catalog:
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@commitlint/lint': ^20.0.0
  '@commitlint/load': ^20.1.0
  '@commitlint/types': ^20.0.0
  '@cspell/cspell-types': ^9.2.1
  '@eslint/config-helpers': ^0.4.0
  '@eslint/config-inspector': ^1.3.0
  '@eslint/js': ^9.37.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@types/minimist': ^1.2.5
  '@types/node': ^20.19.18
  '@types/normalize-package-data': ^2.4.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  cosmiconfig: ^9.0.0
  cosmiconfig-typescript-loader: ^6.2.0
  cspell: ^9.2.1
  escape-string-regexp: ^5.0.0
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-jsdoc: ^61.1.1
  eslint-plugin-n: ^17.23.1
  eslint-plugin-unicorn: ^61.0.2
  execa: ^9.6.0
  find-up: ^8.0.0
  globals: ^16.4.0
  globby: ^15.0.0
  husky: ^9.1.7
  jiti: ^2.6.1
  minimist: ^1.2.8
  normalize-package-data: ^8.0.0
  p-queue: ^9.0.0
  prettier: ^3.6.2
  prettier-plugin-organize-attributes: ^1.0.0
  turbo: ^2.5.8
  type-fest: ^5.0.1
  typedoc: ^0.28.14
  typedoc-github-theme: ^0.3.1
  typedoc-plugin-mdn-links: ^5.0.10
  typedoc-plugin-umami-analytics: ^1.0.1
  typescript: ^5.9.3
  typescript-eslint: ^8.46.0
  vitest: ^3.2.4
  yaml: ^2.8.1
  yoctocolors: ^2.1.1
  zod: ^4.1.12
  zod-validation-error: ^4.0.2

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

onlyBuiltDependencies:
  - esbuild

verifyDepsBeforeRun: prompt
