name: Docs 📘

on:
  repository_dispatch:
    types:
      - release-commit-created
  workflow_dispatch:
    inputs:
      ref:
        description: Ref
        required: false
        default: 'main'

run-name: >
  ${{
    format(
      '{0} {1}',
      github.workflow,
      github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.event.inputs.ref
    )
  }}

concurrency:
  cancel-in-progress: false
  group: >
    ${{
      format(
        '{0}--{1}',
        github.workflow,
        github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.event.inputs.ref
      )
    }}

env:
  REF: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.event.inputs.ref }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: 🪪 Retrieve Credentials
        id: credentials
        uses: simbo-actions/actions/actions/github-app-credentials@main
        with:
          app-id: ${{ secrets.SIMBO_GITHUB_APP_ID }}
          app-private-key: ${{ secrets.SIMBO_GITHUB_APP_PRIVATE_KEY }}

      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.credentials.outputs.token }}
          ref: ${{ env.REF }}

      - name: 🚚 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 👷‍♂️ Build Packages
        run: pnpm run each:build

      - name: 📘 Build Docs
        run: pnpm run docs

      - name: 🚚 Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          git-config-name: ${{ steps.credentials.outputs.name }}
          git-config-email: ${{ steps.credentials.outputs.email }}
          folder: docs
          branch: gh-pages
          clean: true
          single-commit: true
